services:
  mongo:
    image: mongo:latest
    container_name: localhost
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
    networks:
      - gowhisper-network

  gowhisper:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://localhost:27017
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/dist/ 
    networks:
      - gowhisper-network

volumes:
  mongo-data:

networks:
  gowhisper-network:
    driver: bridge